database:
  url: "postgres://user:password@localhost:5432/video_gen?sslmode=disable"
users:
  - email: user1@mail.com
    theme: "Science"
    sources:
      - reddit
    platforms:
      - name: "YouTube"
        credentials: "youtube_credentials.json"
        api_key: "youtube_api_key"
        upload_path: "/videos/youtube/"
      - name: "TikTok"
        credentials: "tiktok_credentials.json"
        api_key: "tiktok_api_key"
        upload_path: "/videos/tiktok/"
    sound:
      name: "freeSound"
      api_key: ""
    stock:
      name: "pexels"
      api_key: ""

#  - email: user2@mail.com
#    theme: "meme"
#    sources:
#      - twitter
#    platforms:
#      - name: "YouTube"
#        credentials: "youtube_credentials.json"
#        api_key: "youtube_api_key"
#        upload_path: "/videos/youtube/"
