FROM golang:1.21 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o uploader ./cmd/uploader

FROM debian:bullseye-slim

WORKDIR /app
COPY --from=builder /app/uploader .

CMD ["./uploader"]
