# Используем Go-образ
FROM golang:1.21 AS builder

WORKDIR /app

# Копируем файлы проекта
COPY go.mod go.sum ./
RUN go mod download

COPY . .

# Собираем бинарник
RUN go build -o generator ./cmd/generator

# Финальный образ
FROM debian:bullseye-slim

WORKDIR /app
COPY --from=builder /app/generator .

CMD ["./generator"]
