version: '3.8'

services:
  gen_sh:
    build: .
    container_name: gen_sh
    volumes:
      - ./data:/app/data
      - ./config:/app/config
    environment:
      - ENV_VAR=value
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db
    command: ["/usr/local/bin/shutdown.sh"]

  db:
    image: postgres:13
    container_name: gen_sh_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gen_sh_db
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
